name: Release
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 6.31.0
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm build
      - run: mv dist/index.js dist/synchrony-${GITHUB_REF_NAME}.js
      - name: Release
        uses: softprops/action-gh-release@v0.1.15
        with:
          files: |
            dist/synchrony-*.js
            dist/deobfuscate.js
          name: Addon
          tag_name: all
          body: Download Here
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
